services:
      pteropal:
        image: nubsuki/pteropal
        container_name: petropal
        ports:
          - "3000:3000"
        environment:
          - DISCORD_TOKEN=# Discord bot token
          - DISCORD_PREFIX=. # Discord bot prefix (default: .)
          - PTERODACTYL_API_URL=# Pterodactyl API URL
          - PTERODACTYL_API_KEY=# Pterodactyl API key
          - FOLDER_NAMES=folder1,folder2  # Comma-separated folder names for backup
          - FOLDER_PATHS=/path/to/folder1,/path/to/folder2  # Corresponding folder paths
          - TZ=Asia/Colombo
          - BACKUP_TIME= # Time for backup 24h format (e.g., 14:30)
          - MAX_BACKUPS=0 # 0 = Keep all backups. > 0 = Keep latest N backups.
          - SHUTDOWN_BEFORE_BACKUP=true # Set to false to disable server shutdown before backup
        volumes:
          - /mnt/pteropal/config/token.json:/app/token.json  # Mount the token file
          - /mnt/pteropal/config/credentials.json:/app/credentials.json  # Mount Google Drive credentials
          - /mnt/pterodactyl/volumes:/pterodactyl/volumes  # Mount the Pterodactyl Save directory
          - /mnt/path/to/host/backups:/app/local_backups # Mount local backup directory
        restart: unless-stopped